title = "AWP | cybersecurity blog"
theme = 'ananke'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
text_color = ""
author = ""
favicon = ""
site_logo = ""
description = "The last theme you'll ever need. Maybe."
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
recent_posts_number = 3
